Add parameters for the gauge
mfts/gauge-demo pull request #2
Opened 2024-04-29 16:22 UTC by thibault0712

This pull request add two parameters :
  -> bgColor : the background color of the gauge
  -> color : the color of the gauge

2024-04-30 03:39 UTC, mfts approved these changes

2024-04-30 03:41 UTC, mfts requested changes

2024-04-30 03:41 UTC, mfts commented on app/gauge.tsx
> +  bgcolor: String;
Can you make these two props optional, otherwise the builds fail as the demo expects these props currently.

2024-04-30 03:41 UTC, mfts commented
Looks great. Thanks for adding these. Small change for typescript :)

2024-04-30 10:10 UTC, thibault0712 commented
it's resolved normally

2024-05-02 05:54 UTC, mfts approved these changes

2024-05-02 05:54 UTC, merged